// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaddleHeroesAirWays.API;

#nullable disable

namespace SaddleHeroesAirWays.API.Migrations
{
    [DbContext(typeof(DbContextAPI))]
    [Migration("20260512131200_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("airport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Stockholm",
                            Country = "Sweden",
                            IATACode = "ARN",
                            Name = "Stockholm Arlanda"
                        },
                        new
                        {
                            Id = 2,
                            City = "London",
                            Country = "UK",
                            IATACode = "LHR",
                            Name = "Heathrow Airport"
                        },
                        new
                        {
                            Id = 3,
                            City = "New York",
                            Country = "USA",
                            IATACode = "JFK",
                            Name = "John F. Kennedy International"
                        },
                        new
                        {
                            Id = 4,
                            City = "Paris",
                            Country = "France",
                            IATACode = "CDG",
                            Name = "Charles de Gaulle"
                        },
                        new
                        {
                            Id = 5,
                            City = "Dubai",
                            Country = "UAE",
                            IATACode = "DXB",
                            Name = "Dubai International"
                        },
                        new
                        {
                            Id = 6,
                            City = "Frankfurt",
                            Country = "Germany",
                            IATACode = "FRA",
                            Name = "Frankfurt Airport"
                        });
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Booking", b =>
                {
                    b.Property<string>("BookingReference")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingReference");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("booking");

                    b.HasData(
                        new
                        {
                            BookingReference = "BKG-1001",
                            BookingDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 1,
                            TotalPrice = 150.00m,
                            UserId = 1
                        },
                        new
                        {
                            BookingReference = "BKG-1002",
                            BookingDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 2,
                            TotalPrice = 600.00m,
                            UserId = 2
                        },
                        new
                        {
                            BookingReference = "BKG-1003",
                            BookingDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 1,
                            FlightId = 3,
                            TotalPrice = 800.00m,
                            UserId = 3
                        },
                        new
                        {
                            BookingReference = "BKG-1004",
                            BookingDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 4,
                            TotalPrice = 200.00m,
                            UserId = 4
                        },
                        new
                        {
                            BookingReference = "BKG-1005",
                            BookingDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 5,
                            TotalPrice = 100.00m,
                            UserId = 5
                        },
                        new
                        {
                            BookingReference = "BKG-1006",
                            BookingDate = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 6,
                            TotalPrice = 500.00m,
                            UserId = 6
                        },
                        new
                        {
                            BookingReference = "BKG-1007",
                            BookingDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 2,
                            FlightId = 7,
                            TotalPrice = 700.00m,
                            UserId = 7
                        },
                        new
                        {
                            BookingReference = "BKG-1008",
                            BookingDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 8,
                            TotalPrice = 120.00m,
                            UserId = 8
                        },
                        new
                        {
                            BookingReference = "BKG-1009",
                            BookingDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 9,
                            TotalPrice = 650.00m,
                            UserId = 9
                        },
                        new
                        {
                            BookingReference = "BKG-1010",
                            BookingDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 10,
                            TotalPrice = 550.00m,
                            UserId = 10
                        },
                        new
                        {
                            BookingReference = "BKG-1011",
                            BookingDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 2,
                            TotalPrice = 600.00m,
                            UserId = 1
                        },
                        new
                        {
                            BookingReference = "BKG-1012",
                            BookingDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookingStatus = 0,
                            FlightId = 7,
                            TotalPrice = 700.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.BookingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Baggage")
                        .HasColumnType("bit");

                    b.Property<string>("BookingReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingReference1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seatnumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference1");

                    b.ToTable("bookingDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baggage = true,
                            BookingReference = "BKG-1001",
                            Notes = "Vegetarian meal requested",
                            Seatnumber = "12A"
                        },
                        new
                        {
                            Id = 2,
                            Baggage = true,
                            BookingReference = "BKG-1002",
                            Notes = "VIP Customer",
                            Seatnumber = "1A"
                        },
                        new
                        {
                            Id = 3,
                            Baggage = false,
                            BookingReference = "BKG-1003",
                            Notes = "",
                            Seatnumber = "15C"
                        },
                        new
                        {
                            Id = 4,
                            Baggage = true,
                            BookingReference = "BKG-1004",
                            Notes = "Needs wheelchair assistance",
                            Seatnumber = "8F"
                        },
                        new
                        {
                            Id = 5,
                            Baggage = false,
                            BookingReference = "BKG-1005",
                            Notes = "Window seat preferred",
                            Seatnumber = "22B"
                        },
                        new
                        {
                            Id = 6,
                            Baggage = true,
                            BookingReference = "BKG-1006",
                            Notes = "Extra legroom paid",
                            Seatnumber = "3A"
                        },
                        new
                        {
                            Id = 7,
                            Baggage = true,
                            BookingReference = "BKG-1007",
                            Notes = "Traveling with pet",
                            Seatnumber = "14D"
                        },
                        new
                        {
                            Id = 8,
                            Baggage = false,
                            BookingReference = "BKG-1008",
                            Notes = "",
                            Seatnumber = "9E"
                        },
                        new
                        {
                            Id = 9,
                            Baggage = true,
                            BookingReference = "BKG-1009",
                            Notes = "Allergic to peanuts",
                            Seatnumber = "2C"
                        },
                        new
                        {
                            Id = 10,
                            Baggage = true,
                            BookingReference = "BKG-1010",
                            Notes = "",
                            Seatnumber = "11A"
                        },
                        new
                        {
                            Id = 11,
                            Baggage = true,
                            BookingReference = "BKG-1011",
                            Notes = "Traveling with VIP",
                            Seatnumber = "1B"
                        },
                        new
                        {
                            Id = 12,
                            Baggage = true,
                            BookingReference = "BKG-1012",
                            Notes = "",
                            Seatnumber = "4F"
                        });
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.ToTable("flight");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalAirportId = 2,
                            ArrivalTime = new DateTime(2026, 6, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 1,
                            DepartureTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-101",
                            FlightStatus = 0,
                            Price = 150.00m,
                            TotalSeats = 150
                        },
                        new
                        {
                            Id = 2,
                            ArrivalAirportId = 3,
                            ArrivalTime = new DateTime(2026, 6, 2, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 2,
                            DepartureTime = new DateTime(2026, 6, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-102",
                            FlightStatus = 1,
                            Price = 600.00m,
                            TotalSeats = 200
                        },
                        new
                        {
                            Id = 3,
                            ArrivalAirportId = 5,
                            ArrivalTime = new DateTime(2026, 6, 6, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 3,
                            DepartureTime = new DateTime(2026, 6, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-103",
                            FlightStatus = 2,
                            Price = 800.00m,
                            TotalSeats = 300
                        },
                        new
                        {
                            Id = 4,
                            ArrivalAirportId = 1,
                            ArrivalTime = new DateTime(2026, 6, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 4,
                            DepartureTime = new DateTime(2026, 6, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-104",
                            FlightStatus = 0,
                            Price = 200.00m,
                            TotalSeats = 120
                        },
                        new
                        {
                            Id = 5,
                            ArrivalAirportId = 2,
                            ArrivalTime = new DateTime(2026, 6, 15, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 6,
                            DepartureTime = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-105",
                            FlightStatus = 0,
                            Price = 100.00m,
                            TotalSeats = 100
                        },
                        new
                        {
                            Id = 6,
                            ArrivalAirportId = 1,
                            ArrivalTime = new DateTime(2026, 6, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 5,
                            DepartureTime = new DateTime(2026, 6, 20, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-106",
                            FlightStatus = 0,
                            Price = 500.00m,
                            TotalSeats = 250
                        },
                        new
                        {
                            Id = 7,
                            ArrivalAirportId = 3,
                            ArrivalTime = new DateTime(2026, 7, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 1,
                            DepartureTime = new DateTime(2026, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-107",
                            FlightStatus = 0,
                            Price = 700.00m,
                            TotalSeats = 200
                        },
                        new
                        {
                            Id = 8,
                            ArrivalAirportId = 4,
                            ArrivalTime = new DateTime(2026, 7, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 2,
                            DepartureTime = new DateTime(2026, 7, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-108",
                            FlightStatus = 0,
                            Price = 120.00m,
                            TotalSeats = 150
                        },
                        new
                        {
                            Id = 9,
                            ArrivalAirportId = 6,
                            ArrivalTime = new DateTime(2026, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 3,
                            DepartureTime = new DateTime(2026, 7, 10, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-109",
                            FlightStatus = 1,
                            Price = 650.00m,
                            TotalSeats = 220
                        },
                        new
                        {
                            Id = 10,
                            ArrivalAirportId = 5,
                            ArrivalTime = new DateTime(2026, 7, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirportId = 4,
                            DepartureTime = new DateTime(2026, 7, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "SH-110",
                            FlightStatus = 0,
                            Price = 550.00m,
                            TotalSeats = 280
                        });
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "arthur.morgan@vandertravel.com",
                            Firstname = "Arthur",
                            Gender = "Male",
                            IsAdmin = false,
                            Lastname = "Morgan",
                            Phonenumber = "555-0101",
                            SocialSecurityNumber = "18630101-1111"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sadie.adler@bountyhunters.com",
                            Firstname = "Sadie",
                            Gender = "Female",
                            IsAdmin = true,
                            Lastname = "Adler",
                            Phonenumber = "555-0102",
                            SocialSecurityNumber = "18650202-2222"
                        },
                        new
                        {
                            Id = 3,
                            Email = "john.marston@ranchers.com",
                            Firstname = "John",
                            Gender = "Male",
                            IsAdmin = false,
                            Lastname = "Marston",
                            Phonenumber = "555-0103",
                            SocialSecurityNumber = "18730303-3333"
                        },
                        new
                        {
                            Id = 4,
                            Email = "dutch@tahitiplans.com",
                            Firstname = "Dutch",
                            Gender = "Male",
                            IsAdmin = true,
                            Lastname = "van der Linde",
                            Phonenumber = "555-0104",
                            SocialSecurityNumber = "18550404-4444"
                        },
                        new
                        {
                            Id = 5,
                            Email = "abigail.roberts@ranchers.com",
                            Firstname = "Abigail",
                            Gender = "Female",
                            IsAdmin = false,
                            Lastname = "Roberts",
                            Phonenumber = "555-0105",
                            SocialSecurityNumber = "18770505-5555"
                        },
                        new
                        {
                            Id = 6,
                            Email = "charles.smith@wanderers.com",
                            Firstname = "Charles",
                            Gender = "Male",
                            IsAdmin = false,
                            Lastname = "Smith",
                            Phonenumber = "555-0106",
                            SocialSecurityNumber = "18680606-6666"
                        },
                        new
                        {
                            Id = 7,
                            Email = "hosea@conartists.com",
                            Firstname = "Hosea",
                            Gender = "Male",
                            IsAdmin = false,
                            Lastname = "Matthews",
                            Phonenumber = "555-0107",
                            SocialSecurityNumber = "18440707-7777"
                        },
                        new
                        {
                            Id = 8,
                            Email = "micah.bell@trouble.com",
                            Firstname = "Micah",
                            Gender = "Male",
                            IsAdmin = false,
                            Lastname = "Bell",
                            Phonenumber = "555-0108",
                            SocialSecurityNumber = "18600808-8888"
                        },
                        new
                        {
                            Id = 9,
                            Email = "lenny.summers@friends.com",
                            Firstname = "Lenny",
                            Gender = "Male",
                            IsAdmin = false,
                            Lastname = "Summers",
                            Phonenumber = "555-0109",
                            SocialSecurityNumber = "18790909-9999"
                        },
                        new
                        {
                            Id = 10,
                            Email = "marybeth@writers.com",
                            Firstname = "Mary-Beth",
                            Gender = "Female",
                            IsAdmin = false,
                            Lastname = "Gaskill",
                            Phonenumber = "555-0110",
                            SocialSecurityNumber = "18781010-0000"
                        });
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Booking", b =>
                {
                    b.HasOne("SaddleHeroesAirWays.Library.Models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaddleHeroesAirWays.Library.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.BookingDetails", b =>
                {
                    b.HasOne("SaddleHeroesAirWays.Library.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingReference1");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Flight", b =>
                {
                    b.HasOne("SaddleHeroesAirWays.Library.Models.Airport", "ArrivalAirport")
                        .WithMany("ArrivingFlights")
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaddleHeroesAirWays.Library.Models.Airport", "DepartureAirport")
                        .WithMany("DepartingFlights")
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Airport", b =>
                {
                    b.Navigation("ArrivingFlights");

                    b.Navigation("DepartingFlights");
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SaddleHeroesAirWays.Library.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
